# version: "3.9"
services:
  rag_api_dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: rag-api-dev
    volumes:
      - ../:/app
    env_file:
      - ../.env
    ports:
      - "7001:8001"
    restart: unless-stopped


  rag_api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: rag-api-prod
    env_file:
      - ../.env
    ports:
      - "8001:8001"
    restart: unless-stopped