version: "3.9"
services:
  rag_api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: rag_api
    env_file:
      - ../.env   # must contain PG_HOST=34.166.56.20, PG_PORT=5432, PG_USER=..., PG_PASSWORD=..., PG_DB=..., PG_SCHEMA=...
    ports:
      - "8010:8010"
    restart: unless-stopped
